import Foundation
import simd

/// G-code fatiado (Bambu Studio, Orca, PrusaSlicer): metadados, thumbnail embutida e caminho de extrusão.
public enum GCode {
    public struct Metadata {
        public var info = ThreeMFInfo()
        /// Maior PNG/JPG embutido (`; thumbnail begin WxH len` … `; thumbnail end`).
        public var thumbnail: Data?
        public var generator: String?
    }

    static let headBytes = 2_000_000
    static let tailBytes = 1_000_000

    public static func metadata(url: URL) throws -> Metadata {
        let data = try Data(contentsOf: url, options: .alwaysMapped)
        let head = String(decoding: data.prefix(headBytes), as: UTF8.self)
        let tail = data.count > headBytes ? String(decoding: data.suffix(tailBytes), as: UTF8.self) : ""
        var meta = Metadata()
        meta.thumbnail = largestThumbnail(in: head)
        meta.generator = head.firstMatch(#"(?m)^; generated by ([^\n]+)"#)
        let config = head + "\n" + tail
        func value(_ key: String) -> String? {
            config.firstMatch("(?m)^; \(key) = ([^\\n]*)$").map { $0.trimmingCharacters(in: .whitespaces) }
        }
        meta.info.printerModel = value("printer_model").flatMap { $0.isEmpty ? nil : $0 }
        meta.info.printerSettingsID = value("printer_settings_id")
        meta.info.printSettingsID = value("print_settings_id") ?? meta.generator
        meta.info.filamentColours = (value("filament_colour") ?? value("extruder_colour") ?? "")
            .split(whereSeparator: { $0 == ";" || $0 == "," }).map { String($0).trimmingCharacters(in: .whitespaces) }
        if let area = value("printable_area") ?? value("bed_shape") {
            let pts = area.split(separator: ",").compactMap { s -> SIMD2<Double>? in
                let p = s.split(separator: "x").compactMap { Double($0) }
                return p.count == 2 ? SIMD2(p[0], p[1]) : nil
            }
            if pts.count >= 3 {
                meta.info.bedMin = pts.reduce(pts[0]) { simd_min($0, $1) }
                meta.info.bedMax = pts.reduce(pts[0]) { simd_max($0, $1) }
            }
        }
        return meta
    }

    static func largestThumbnail(in head: String) -> Data? {
        var best: (area: Int, data: Data)?
        let pattern = #"(?s); thumbnail(?:_(PNG|JPG))? begin (\d+)x(\d+) \d+\n(.*?); thumbnail(?:_(?:PNG|JPG))? end"#
        guard let re = try? NSRegularExpression(pattern: pattern) else { return nil }
        let ns = head as NSString
        for m in re.matches(in: head, range: NSRange(location: 0, length: ns.length)) {
            let w = Int(ns.substring(with: m.range(at: 2))) ?? 0, h = Int(ns.substring(with: m.range(at: 3))) ?? 0
            let body = ns.substring(with: m.range(at: 4))
                .split(separator: "\n").map { $0.drop(while: { $0 == ";" || $0 == " " }) }.joined()
            guard let data = Data(base64Encoded: body), w * h > (best?.area ?? 0) else { continue }
            best = (w * h, data)
        }
        return best?.data
    }

    /// Caminho de extrusão em coordenadas da mesa, uma lista de segmentos (pares de pontos) por cor.
    public static func toolpath(url: URL, info: ThreeMFInfo, maxSegments: Int = 1_500_000) throws -> PrintScene {
        let data = try Data(contentsOf: url, options: .alwaysMapped)
        var scene = PrintScene()
        scene.beds = PrintScene.bedLayout(count: 1, min: info.bedMin, max: info.bedMax)
        func colour(_ tool: Int) -> String {
            let list = info.filamentColours.filter { $0.hasPrefix("#") && $0.count >= 7 }
            guard !list.isEmpty else { return "#B8B4AC" }
            return String(list[Swift.max(0, Swift.min(list.count - 1, tool))].prefix(7)).uppercased()
        }

        var pos = SIMD3<Float>(0, 0, 0), e: Float = 0
        var absolute = true, absoluteE = true, tool = 0
        var segments: [Int: [SIMD3<Float>]] = [:]
        var count = 0

        data.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let bytes = raw.bindMemory(to: UInt8.self)
            var i = 0
            let n = bytes.count
            while i < n {
                var end = i
                while end < n && bytes[end] != 10 { end += 1 }
                defer { i = end + 1 }
                var j = i
                while j < end && bytes[j] == 32 { j += 1 }
                guard j < end else { continue }
                let c0 = bytes[j]
                if c0 == 84 /* T */ {
                    if let t = number(bytes, j + 1, end).value { tool = Int(t) }
                    continue
                }
                guard c0 == 71 /* G */ || c0 == 77 /* M */ else { continue }
                guard let code = number(bytes, j + 1, end).value else { continue }
                if c0 == 77 {
                    if code == 82 { absoluteE = true } else if code == 83 { absoluteE = false }
                    continue
                }
                switch Int(code) {
                case 90: absolute = true
                case 91: absolute = false
                case 92:
                    var k = j + 1
                    while k < end {
                        let ch = bytes[k]
                        if ch == 59 { break }
                        if ch == 69 /* E */, let v = number(bytes, k + 1, end).value { e = v }
                        k += 1
                    }
                case 0, 1, 2, 3:
                    var next = pos, de: Float = 0, hasE = false
                    var k = j + 1
                    while k < end {
                        let ch = bytes[k]
                        if ch == 59 { break } // comentário
                        if ch == 88 || ch == 89 || ch == 90 || ch == 69 {
                            let parsed = number(bytes, k + 1, end)
                            if let v = parsed.value {
                                switch ch {
                                case 88: next.x = absolute ? v : pos.x + v
                                case 89: next.y = absolute ? v : pos.y + v
                                case 90: next.z = absolute ? v : pos.z + v
                                default:
                                    hasE = true
                                    de = absoluteE ? v - e : v
                                    e = absoluteE ? v : e + v
                                }
                            }
                            k = parsed.end
                            continue
                        }
                        k += 1
                    }
                    if hasE && de > 0 && (next.x != pos.x || next.y != pos.y) {
                        segments[tool, default: []] += [pos, next]
                        count += 1
                    }
                    pos = next
                default:
                    break
                }
            }
        }

        let stride = Swift.max(1, (count + maxSegments - 1) / maxSegments)
        for (t, points) in segments {
            var kept: [SIMD3<Float>] = []
            kept.reserveCapacity(points.count / stride + 2)
            var s = 0
            while s + 1 < points.count {
                kept.append(points[s]); kept.append(points[s + 1])
                scene.boundsMin = simd_min(scene.boundsMin, simd_min(points[s], points[s + 1]))
                scene.boundsMax = simd_max(scene.boundsMax, simd_max(points[s], points[s + 1]))
                s += 2 * stride
            }
            scene.lines[colour(t), default: []] += kept
        }
        return scene
    }

    /// Lê um número decimal a partir de `start`; devolve o valor e onde parou.
    static func number(_ b: UnsafeBufferPointer<UInt8>, _ start: Int, _ end: Int) -> (value: Float?, end: Int) {
        var k = start, sign: Float = 1, value: Float = 0, scale: Float = 0, digits = 0
        if k < end && (b[k] == 45 || b[k] == 43) { sign = b[k] == 45 ? -1 : 1; k += 1 }
        while k < end {
            let ch = b[k]
            if ch >= 48 && ch <= 57 {
                if scale == 0 { value = value * 10 + Float(ch - 48) } else { value += Float(ch - 48) * scale; scale *= 0.1 }
                digits += 1
            } else if ch == 46 && scale == 0 {
                scale = 0.1
            } else { break }
            k += 1
        }
        return (digits > 0 ? sign * value : nil, k)
    }
}
